
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/onsi/ginkgo/ginkgo"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/groot"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  version = "1.0.1"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/Microsoft/hcsshim"
  source = "github.com/greenhouse-org/hcsshim"
  branch = "v0.8.3-mod"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.7"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/hydrator"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/filelock"

# This is done to address an issue with dep
# See https://github.com/golang/dep/issues/1799
[[override]]
  source = "https://github.com/fsnotify/fsnotify"
  name = "gopkg.in/fsnotify.v1"
